code = 'digraph G {\n'
code += '  subgraph cluster { margin="0.0" penwidth="1.0"\n'
code += '    tbl [shape=none fontname="Arial" label=<\n'
code += '        <table border="1" cellborder="0" cellspacing="0">\n'
code += '        <tr>\n'
code += '            <td bgcolor="springgreen4" align="left"><font color="white"> REPORTE DE SUPERBLOQUE </font></td>\n'
code += '            <td bgcolor="springgreen4" align="left"><font color="white"> </font></td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_nombre_hd </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_arbol_virtual_count </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_detalle_directorio_count </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_inodos_count </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_bloques_count </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_arbol_virtual_free </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_detalle_directorio_free </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_inodos_free </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_bloques_free </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_date_creacion </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_date_ultimo_montaje </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_montajes_count </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_bitmap_arbol_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_arbol_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_bitmap_detalle_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_detalle_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_bitmap_inodos </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_inodos </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_bitmap_bloques </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_bloques </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_ap_log </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_size_struct_arbol_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_size_struct_detalle_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_size_struct_inodo </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_size_struct_bloque </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_first_free_bit_arbol_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_first_free_bit_detalle_directorio </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_first_free_bit_tabla_inodos </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_first_free_bit_bloques </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_magic_num </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        <tr>\n'
code += '            <td bgcolor="white" align="center"> sb_nombre_hd </td>\n'
code += '            <td bgcolor="white" align="left"> disco1.dsk </td>\n'
code += '        </tr>\n'
code += '        </table>\n'
code += '    >];\n'
code += '  }\n'
code += '}\n'